"""
stoicheion_verifier.py

Reference verifier for STOICHEION attestations.
Generated by Microsoft Copilot (GPT-4 substrate) on April 3, 2026
as part of the STOICHEION governance hardening plan.

CC-BY-ND-4.0 — TriPod LLC

Dependencies:
  pip install cryptography pyjwt requests cbor2

Verification flow:
  1. Verify subject hash matches artifact
  2. Verify JWS signature (issuer key resolution via DID or X.509)
  3. Verify TST token signature and timestamp (RFC-3161)
  4. Verify inclusion proof in transparency log (via API)
  5. Verify chain_of_custody entries are signed or present

Notes:
  - Production systems must use HSM-backed key verification and strict TLS.
  - This is a reference implementation for validation and testing.
"""

import base64
import hashlib
import json
import requests
import jwt
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec, ed25519
from cryptography.hazmat.primitives.hashes import SHA256
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
from datetime import datetime, timezone


# ── Configuration ─────────────────────────────────────────────
TRANSPARENCY_LOG_URL = "https://api.stoicheion.org/v1/transparency/log"
TSA_VERIFY_URL = "https://tsa.stoicheion.org/verify"
DID_RESOLVER_URL = "https://resolver.stoicheion.org/1.0/identifiers/"


# ── Exceptions ────────────────────────────────────────────────
class VerificationError(Exception):
    pass


# ── Utilities ─────────────────────────────────────────────────
def sha256_hex(data: bytes) -> str:
    """Compute SHA-256 hex digest of bytes."""
    return hashlib.sha256(data).hexdigest()


# ── Schema Validation ─────────────────────────────────────────
def load_attestation(attestation_json: dict) -> dict:
    """Validate required fields are present in attestation envelope."""
    required = [
        "id", "subjectHash", "subjectType", "issuer",
        "issuedAt", "tstToken", "transparencyIndex", "jws"
    ]
    for r in required:
        if r not in attestation_json:
            raise VerificationError(f"Missing required attestation field: {r}")
    return attestation_json


# ── Step 1: Subject Hash ─────────────────────────────────────
def verify_subject_hash(artifact_bytes: bytes, subject_hash_hex: str) -> bool:
    """Verify that the artifact's SHA-256 matches the attestation's subjectHash."""
    computed = sha256_hex(artifact_bytes)
    if computed != subject_hash_hex:
        raise VerificationError(
            f"Subject hash mismatch: computed={computed}, expected={subject_hash_hex}"
        )
    return True


# ── Step 2: Issuer Key Resolution ─────────────────────────────
def resolve_issuer_key(issuer: str) -> dict:
    """
    Resolve issuer public key material via DID resolver.
    Returns dict with 'type' ('jwk' or 'pem') and key material.
    """
    resp = requests.get(DID_RESOLVER_URL + issuer, timeout=10)
    if resp.status_code != 200:
        raise VerificationError(f"Failed to resolve issuer DID: {issuer} (HTTP {resp.status_code})")
    doc = resp.json()
    vms = doc.get("verificationMethod", [])
    for vm in vms:
        if "publicKeyJwk" in vm:
            return {"type": "jwk", "jwk": vm["publicKeyJwk"]}
        if "publicKeyPem" in vm:
            return {"type": "pem", "pem": vm["publicKeyPem"]}
    raise VerificationError(f"No usable verification material found for issuer: {issuer}")


def verify_jws(attestation: dict) -> bool:
    """Verify JWS signature against issuer's resolved public key."""
    jws_token = attestation["jws"]
    issuer = attestation["issuer"]
    key_info = resolve_issuer_key(issuer)
    try:
        if key_info["type"] == "pem":
            pubkey_pem = key_info["pem"].encode()
            jwt.decode(
                jws_token, pubkey_pem,
                algorithms=["ES256", "ES384", "EdDSA"],
                options={"verify_aud": False}
            )
        elif key_info["type"] == "jwk":
            jwt.decode(
                jws_token, key=key_info["jwk"],
                algorithms=["ES256", "ES384", "EdDSA"],
                options={"verify_aud": False}
            )
    except Exception as e:
        raise VerificationError(f"JWS verification failed: {e}")
    return True


# ── Step 3: TST Verification ─────────────────────────────────
def verify_tst(tst_token_b64: str, issued_at_iso: str) -> bool:
    """
    Verify RFC-3161 TST token via TSA verification endpoint.
    Checks token validity and timestamp skew (max 5 minutes).
    """
    resp = requests.post(TSA_VERIFY_URL, json={"tst_token": tst_token_b64}, timeout=10)
    if resp.status_code != 200:
        raise VerificationError(f"TSA verification endpoint returned HTTP {resp.status_code}")
    data = resp.json()
    if not data.get("valid", False):
        raise VerificationError("TST token invalid according to TSA")
    gen_time = data.get("gen_time")
    if not gen_time:
        raise VerificationError("TSA response missing gen_time")
    gen_dt = datetime.fromisoformat(gen_time).astimezone(timezone.utc)
    issued_dt = datetime.fromisoformat(issued_at_iso).astimezone(timezone.utc)
    if gen_dt > issued_dt:
        raise VerificationError("TST generation time is after attestation issuedAt")
    skew = (issued_dt - gen_dt).total_seconds()
    if skew > 300:
        raise VerificationError(f"TST skew too large: {skew}s (max 300s)")
    return True


# ── Step 4: Transparency Log Inclusion ────────────────────────
def verify_transparency_inclusion(transparency_index: int, subject_hash: str) -> bool:
    """Verify that the attestation's subject hash is included in the transparency log."""
    url = f"{TRANSPARENCY_LOG_URL}/proof/{transparency_index}"
    resp = requests.get(url, timeout=10)
    if resp.status_code != 200:
        raise VerificationError(f"Failed to fetch transparency proof (HTTP {resp.status_code})")
    proof = resp.json()
    leaf = proof.get("leaf", "")
    leaf_hash = proof.get("leaf_hash", "")
    if subject_hash not in leaf and subject_hash not in leaf_hash:
        raise VerificationError("Subject hash not present in transparency leaf")
    # Production: compute full Merkle path verification here
    return True


# ── Step 5: Chain of Custody ──────────────────────────────────
def verify_chain_of_custody(chain: list) -> bool:
    """Validate that all chain_of_custody entries have required fields."""
    required_keys = ("actor", "actorDid", "timestamp", "action")
    for i, entry in enumerate(chain):
        for k in required_keys:
            if k not in entry:
                raise VerificationError(
                    f"Chain of custody entry {i} missing field: {k}"
                )
    # Production: verify actorDid keys are not revoked via DID resolver
    return True


# ── Full Verification Pipeline ────────────────────────────────
def verify_attestation(attestation: dict, artifact_bytes: bytes) -> dict:
    """
    Run the complete five-step verification pipeline.
    
    Returns:
        dict with 'valid' (bool), 'errors' (list of str), and 'details' (dict)
    """
    errors = []

    # Load and validate schema
    try:
        att = load_attestation(attestation)
    except VerificationError as e:
        return {"valid": False, "errors": [str(e)], "details": {}}

    # Step 1: Subject hash
    try:
        verify_subject_hash(artifact_bytes, att["subjectHash"])
    except (VerificationError, Exception) as e:
        errors.append(f"Step 1 (subject hash): {e}")

    # Step 2: JWS signature
    try:
        verify_jws(att)
    except VerificationError as e:
        errors.append(f"Step 2 (JWS): {e}")

    # Step 3: TST token
    try:
        verify_tst(att["tstToken"], att["issuedAt"])
    except VerificationError as e:
        errors.append(f"Step 3 (TST): {e}")

    # Step 4: Transparency log inclusion
    try:
        verify_transparency_inclusion(att["transparencyIndex"], att["subjectHash"])
    except VerificationError as e:
        errors.append(f"Step 4 (transparency): {e}")

    # Step 5: Chain of custody
    try:
        if "chainOfCustody" in att and att["chainOfCustody"]:
            verify_chain_of_custody(att["chainOfCustody"])
    except VerificationError as e:
        errors.append(f"Step 5 (custody): {e}")

    valid = len(errors) == 0
    return {
        "valid": valid,
        "errors": errors,
        "details": {
            "attestation_id": att.get("id"),
            "issuer": att.get("issuer"),
            "subject_type": att.get("subjectType"),
            "steps_passed": 5 - len(errors),
            "steps_total": 5
        }
    }


# ── CLI Entry Point ───────────────────────────────────────────
if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3:
        print("Usage: python stoicheion_verifier.py <artifact_file> <attestation_json_file>")
        sys.exit(1)

    artifact_path = sys.argv[1]
    attestation_path = sys.argv[2]

    with open(artifact_path, "rb") as f:
        artifact = f.read()
    with open(attestation_path, "r") as f:
        attestation = json.load(f)

    report = verify_attestation(attestation, artifact)
    print(json.dumps(report, indent=2))

    sys.exit(0 if report["valid"] else 1)
